# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_forms/auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName('StartWindow')
        StartWindow.resize(500, 412)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setStyleSheet('background-color: rgb(56, 55, 52);')
        self.centralwidget.setObjectName('centralwidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.title_bar = QtWidgets.QFrame(self.centralwidget)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_bar.setStyleSheet('QFrame {\n'
                                     '    border:none;\n'
                                     '\n'
                                     '    background-color: rgb(85, 87, 83);\n'
                                     '}\n'
                                     '')
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName('title_bar')
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName('frame_title')
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout_4.setObjectName('gridLayout_4')
        self.label = QtWidgets.QLabel(self.frame_title)
        self.label.setStyleSheet("font: 75 11pt \"Ubuntu Mono\";\n"
                                 'font: bold;\n'
                                 '')
        self.label.setObjectName('label')
        self.gridLayout_4.addWidget(
            self.label, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName('frame_btns')
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.btn_hide = QtWidgets.QPushButton(self.frame_btns)
        self.btn_hide.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_hide.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_hide.setStyleSheet('QPushButton {\n'
                                    '    background-color: rgb(237, 212, 0);\n'
                                    '    border: none;\n'
                                    '    border-radius: 10px;\n'
                                    '    border-style: solid;\n'
                                    '    border-color: rgb(0, 0, 0);\n'
                                    '    border-width: 1px;\n'
                                    '\n'
                                    '}\n'
                                    'QPushButton:hover {\n'
                                    '    background-color: rgb(196, 160, 0);\n'
                                    '}\n'
                                    '\n'
                                    '\n'
                                    '')
        self.btn_hide.setText('')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ':/custom/custom/icons8-horizontal-line-24.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hide.setIcon(icon)
        self.btn_hide.setIconSize(QtCore.QSize(16, 16))
        self.btn_hide.setObjectName('btn_hide')
        self.horizontalLayout_3.addWidget(self.btn_hide)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_close.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_close.setStyleSheet('QPushButton {\n'
                                     '    border: none;\n'
                                     '    border-radius: 10px;\n'
                                     '    background-color: rgb(204, 0, 0);\n'
                                     '    border-style: solid;\n'
                                     '    border-color: rgb(0, 0, 0);\n'
                                     '    border-width: 1px;\n'
                                     '}\n'
                                     'QPushButton:hover {\n'
                                     '    background-color: rgb(164, 0, 0);\n'
                                     '}')
        self.btn_close.setText('')
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            ':/custom/custom/icons8-close.svg'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setObjectName('btn_close')
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header.setStyleSheet('border:none;')
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName('header')
        self.gridLayout = QtWidgets.QGridLayout(self.header)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName('gridLayout')
        self.program_name = QtWidgets.QLabel(self.header)
        self.program_name.setStyleSheet('font: bold;\n'
                                        'font-size: 36px;\n'
                                        'height: 48px;\n'
                                        'width: 120px;\n'
                                        'text-align: center;')
        self.program_name.setObjectName('program_name')
        self.gridLayout.addWidget(
            self.program_name, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet('QFrame {\n'
                                     'border: 0;\n'
                                     '}\n'
                                     '')
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName('main_body')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.body = QtWidgets.QFrame(self.main_body)
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName('body')
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName('verticalLayout_4')
        self.UpperSpacer = QtWidgets.QFrame(self.body)
        self.UpperSpacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UpperSpacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UpperSpacer.setObjectName('UpperSpacer')
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.UpperSpacer)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.LeftSpacer = QtWidgets.QFrame(self.UpperSpacer)
        self.LeftSpacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftSpacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftSpacer.setObjectName('LeftSpacer')
        self.horizontalLayout_4.addWidget(self.LeftSpacer)
        self.sign_in_form = QtWidgets.QFrame(self.UpperSpacer)
        self.sign_in_form.setStyleSheet('QFrame {\n'
                                        '    border-style: solid;\n'
                                        '    border-color: rgb(0, 0, 0);\n'
                                        '    border-width: 1px;\n'
                                        '    border-radius: 8px;\n'
                                        '    background-color: rgb(40, 38, 38);\n'
                                        '}\n'
                                        '')
        self.sign_in_form.setFrameShape(QtWidgets.QFrame.HLine)
        self.sign_in_form.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sign_in_form.setObjectName('sign_in_form')
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sign_in_form)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.label_sign_in = QtWidgets.QLabel(self.sign_in_form)
        self.label_sign_in.setStyleSheet('border-width: 0px;\n'
                                         '')
        self.label_sign_in.setObjectName('label_sign_in')
        self.verticalLayout_3.addWidget(self.label_sign_in)
        self.label_error = QtWidgets.QLabel(self.sign_in_form)
        self.label_error.setStyleSheet('border-width: 0px;\n'
                                       'color: rgb(240, 14, 14);\n'
                                       'font-weight: bold;\n'
                                       '')
        self.label_error.setText('')
        self.label_error.setObjectName('label_error')
        self.verticalLayout_3.addWidget(
            self.label_error, 0, QtCore.Qt.AlignHCenter)
        self.combo_username = QtWidgets.QComboBox(self.sign_in_form)
        self.combo_username.setStyleSheet('QComboBox {\n'
                                          '    border: 1px solid gray;\n'
                                          '    border-radius: 3px;\n'
                                          '    padding: 1px 18px 1px 3px;\n'
                                          '    min-width: 6em;\n'
                                          '}\n'
                                          '\n'
                                          'QComboBox:editable {\n'
                                          '    background: white;\n'
                                          '}\n'
                                          '\n'
                                          'QComboBox:!editable, QComboBox::drop-down:editable {\n'
                                          '     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n'
                                          '                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n'
                                          '                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n'
                                          '}\n'
                                          '\n'
                                          "/* QComboBox gets the \"on\" state when the popup is open */\n"
                                          'QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n'
                                          '    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n'
                                          '                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n'
                                          '                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n'
                                          '}\n'
                                          '\n'
                                          'QComboBox:on { /* shift the text when the popup opens */\n'
                                          '    padding-top: 3px;\n'
                                          '    padding-left: 4px;\n'
                                          '}\n'
                                          '\n'
                                          'QComboBox::drop-down {\n'
                                          '    subcontrol-origin: padding;\n'
                                          '    subcontrol-position: top right;\n'
                                          '    width: 15px;\n'
                                          '\n'
                                          '    border-left-width: 1px;\n'
                                          '    border-left-color: darkgray;\n'
                                          '    border-left-style: solid; /* just a single line */\n'
                                          '    border-top-right-radius: 3px; /* same radius as the QComboBox */\n'
                                          '    border-bottom-right-radius: 3px;\n'
                                          '}\n'
                                          '\n'
                                          'QComboBox::down-arrow {\n'
                                          '    image: url(/usr/share/icons/crystalsvg/16x16/actions/1downarrow.png);\n'
                                          '}\n'
                                          '\n'
                                          'QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n'
                                          '    top: 1px;\n'
                                          '    left: 1px;\n'
                                          '}\n'
                                          'QComboBox QAbstractItemView {\n'
                                          '    border: 2px solid darkgray;\n'
                                          '    selection-background-color: lightgray;\n'
                                          '}')
        self.combo_username.setObjectName('combo_username')
        self.combo_username.addItem('')
        self.combo_username.setItemText(0, '')
        self.combo_username.addItem('')
        self.verticalLayout_3.addWidget(self.combo_username)
        self.sign_in_btn = QtWidgets.QPushButton(self.sign_in_form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.sign_in_btn.sizePolicy().hasHeightForWidth())
        self.sign_in_btn.setSizePolicy(sizePolicy)
        self.sign_in_btn.setMinimumSize(QtCore.QSize(350, 30))
        self.sign_in_btn.setStyleSheet('background-color: rgb(13, 118, 29);')
        self.sign_in_btn.setObjectName('sign_in_btn')
        self.verticalLayout_3.addWidget(self.sign_in_btn)
        self.horizontalLayout_4.addWidget(self.sign_in_form)
        self.RightSpacer = QtWidgets.QFrame(self.UpperSpacer)
        self.RightSpacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightSpacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightSpacer.setObjectName('RightSpacer')
        self.horizontalLayout_4.addWidget(self.RightSpacer)
        self.verticalLayout_4.addWidget(self.UpperSpacer)
        self.DownSpacer = QtWidgets.QFrame(self.body)
        self.DownSpacer.setEnabled(False)
        self.DownSpacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DownSpacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DownSpacer.setObjectName('DownSpacer')
        self.verticalLayout_4.addWidget(self.DownSpacer)
        self.verticalLayout_2.addWidget(self.body)
        self.verticalLayout.addWidget(self.main_body)
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.footer.setStyleSheet('border:none')
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName('footer')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.version = QtWidgets.QFrame(self.footer)
        self.version.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.version.setFrameShadow(QtWidgets.QFrame.Raised)
        self.version.setObjectName('version')
        self.gridLayout_3 = QtWidgets.QGridLayout(self.version)
        self.gridLayout_3.setObjectName('gridLayout_3')
        self.label_version = QtWidgets.QLabel(self.version)
        self.label_version.setObjectName('label_version')
        self.gridLayout_3.addWidget(self.label_version, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.version)
        self.author = QtWidgets.QFrame(self.footer)
        self.author.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.author.setFrameShadow(QtWidgets.QFrame.Raised)
        self.author.setObjectName('author')
        self.gridLayout_2 = QtWidgets.QGridLayout(self.author)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.label_author = QtWidgets.QLabel(self.author)
        self.label_author.setObjectName('label_author')
        self.gridLayout_2.addWidget(self.label_author, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.author)
        self.verticalLayout.addWidget(self.footer)
        StartWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate('StartWindow', 'MainWindow'))
        self.label.setText(_translate('StartWindow', 'SteamNameChanger'))
        self.program_name.setText(_translate(
            'StartWindow', 'SteamNameChanger'))
        self.label_sign_in.setText(_translate(
            'StartWindow',
            "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Sign in</span></p></body></html>"))
        self.combo_username.setItemText(1, _translate(
            'StartWindow', 'Add a new account...'))
        self.sign_in_btn.setText(_translate('StartWindow', 'Sign in'))
        self.label_version.setText(_translate('StartWindow', 'v.1.0'))
        self.label_author.setText(_translate(
            'StartWindow', "<html><head/><body><p align=\"right\">by NightExpress</p></body></html>"))
