# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/skeletons/ui_forms/start.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWin(object):
    def setupUi(self, StartWin):
        StartWin.setObjectName('StartWin')
        StartWin.resize(332, 474)
        self.centralwidget = QtWidgets.QWidget(StartWin)
        self.centralwidget.setStyleSheet('border: none;\n'
                                         'background-color: rgb(56, 55, 52);')
        self.centralwidget.setObjectName('centralwidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.title_bar = QtWidgets.QFrame(self.centralwidget)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 40))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_bar.setStyleSheet('QFrame {\n'
                                     '    border:none;\n'
                                     '    \n'
                                     '    background-color: rgb(85, 87, 83);\n'
                                     '}\n'
                                     '')
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName('title_bar')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName('frame_title')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.label = QtWidgets.QLabel(self.frame_title)
        self.label.setStyleSheet("font: 75 11pt \"Ubuntu Mono\";\n"
                                 'font: bold;\n'
                                 '')
        self.label.setObjectName('label')
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName('frame_btns')
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.btn_hide = QtWidgets.QPushButton(self.frame_btns)
        self.btn_hide.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_hide.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_hide.setStyleSheet('QPushButton {\n'
                                    '    background-color: rgb(237, 212, 0);\n'
                                    '    border: none;\n'
                                    '    border-radius: 10px;\n'
                                    '    border-style: solid;\n'
                                    '    border-color: rgb(0, 0, 0);\n'
                                    '    border-width: 1px;\n'
                                    '    \n'
                                    '}\n'
                                    'QPushButton:hover {\n'
                                    '    background-color: rgb(196, 160, 0);\n'
                                    '}\n'
                                    '\n'
                                    '\n'
                                    '')
        self.btn_hide.setText('')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ':/custom/custom/icons8-horizontal-line-24.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hide.setIcon(icon)
        self.btn_hide.setIconSize(QtCore.QSize(16, 16))
        self.btn_hide.setObjectName('btn_hide')
        self.horizontalLayout_2.addWidget(self.btn_hide)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_close.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_close.setStyleSheet('QPushButton {\n'
                                     '    border: none;\n'
                                     '    border-radius: 10px;\n'
                                     '    background-color: rgb(204, 0, 0);\n'
                                     '    border-style: solid;\n'
                                     '    border-color: rgb(0, 0, 0);\n'
                                     '    border-width: 1px;\n'
                                     '}\n'
                                     'QPushButton:hover {\n'
                                     '    background-color: rgb(164, 0, 0);\n'
                                     '}')
        self.btn_close.setText('')
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            ':/custom/custom/icons8-close.svg'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setObjectName('btn_close')
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName('body')
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.label_username = QtWidgets.QLabel(self.body)
        self.label_username.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_username.setStyleSheet('font: bold;\n'
                                          'font-size: 30px;\n'
                                          'height: 48px;\n'
                                          'width: 120px;')
        self.label_username.setObjectName('label_username')
        self.verticalLayout_3.addWidget(
            self.label_username, 0, QtCore.Qt.AlignHCenter)
        self.Time = QtWidgets.QFrame(self.body)
        self.Time.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Time.setStyleSheet('QFrame {\n'
                                '    border-style: solid;\n'
                                '    border-color: rgb(0, 0, 0);\n'
                                '    border-width: 1px;\n'
                                '    border-radius: 8px;\n'
                                '    background-color: rgb(40, 38, 38);\n'
                                '}\n'
                                '')
        self.Time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Time.setObjectName('Time')
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Time)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.label_3 = QtWidgets.QLabel(self.Time)
        self.label_3.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_3.setStyleSheet('border:none;\n'
                                   'color:white')
        self.label_3.setObjectName('label_3')
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.Time)
        self.comboBox.setStyleSheet('QComboBox {\n'
                                    '    border: 1px solid gray;\n'
                                    '    border-radius: 3px;\n'
                                    '    padding: 1px 18px 1px 3px;\n'
                                    '    min-width: 6em;\n'
                                    '}\n'
                                    '\n'
                                    'QComboBox:editable {\n'
                                    '    background: white;\n'
                                    '}\n'
                                    '\n'
                                    'QComboBox:!editable, QComboBox::drop-down:editable {\n'
                                    '     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n'
                                    '                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n'
                                    '                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n'
                                    '}\n'
                                    '\n'
                                    "/* QComboBox gets the \"on\" state when the popup is open */\n"
                                    'QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n'
                                    '    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n'
                                    '                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n'
                                    '                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n'
                                    '}\n'
                                    '\n'
                                    'QComboBox:on { /* shift the text when the popup opens */\n'
                                    '    padding-top: 3px;\n'
                                    '    padding-left: 4px;\n'
                                    '}\n'
                                    '\n'
                                    'QComboBox::drop-down {\n'
                                    '    subcontrol-origin: padding;\n'
                                    '    subcontrol-position: top right;\n'
                                    '    width: 15px;\n'
                                    '\n'
                                    '    border-left-width: 1px;\n'
                                    '    border-left-color: darkgray;\n'
                                    '    border-left-style: solid; /* just a single line */\n'
                                    '    border-top-right-radius: 3px; /* same radius as the QComboBox */\n'
                                    '    border-bottom-right-radius: 3px;\n'
                                    '}\n'
                                    '\n'
                                    'QComboBox::down-arrow {\n'
                                    '    image: url(/usr/share/icons/crystalsvg/16x16/actions/1downarrow.png);\n'
                                    '}\n'
                                    '\n'
                                    'QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n'
                                    '    top: 1px;\n'
                                    '    left: 1px;\n'
                                    '}\n'
                                    'QComboBox QAbstractItemView {\n'
                                    '    border: 2px solid darkgray;\n'
                                    '    selection-background-color: lightgray;\n'
                                    '}')
        self.comboBox.setObjectName('comboBox')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_3.addWidget(self.Time)
        self.type_changing = QtWidgets.QFrame(self.body)
        self.type_changing.setStyleSheet('QFrame {\n'
                                         '    border-style: solid;\n'
                                         '    border-color: rgb(0, 0, 0);\n'
                                         '    border-width: 1px;\n'
                                         '    border-radius: 8px;\n'
                                         '    background-color: rgb(40, 38, 38);\n'
                                         '}\n'
                                         '')
        self.type_changing.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.type_changing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.type_changing.setObjectName('type_changing')
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.type_changing)
        self.verticalLayout_5.setObjectName('verticalLayout_5')
        self.label_types = QtWidgets.QLabel(self.type_changing)
        self.label_types.setStyleSheet('border:none;\n'
                                       'color:white')
        self.label_types.setObjectName('label_types')
        self.verticalLayout_5.addWidget(self.label_types)
        self.types = QtWidgets.QFrame(self.type_changing)
        self.types.setStyleSheet('border:none;\n'
                                 'color:white')
        self.types.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.types.setFrameShadow(QtWidgets.QFrame.Raised)
        self.types.setObjectName('types')
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.types)
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.ordinal = QtWidgets.QRadioButton(self.types)
        self.ordinal.setStyleSheet('    border-style: solid;\n'
                                   '    border-color: rgb(0, 0, 0);\n'
                                   '    border-width: 1px;\n'
                                   '    border-radius: 8px;\n'
                                   'background-color: rgb(85, 87, 83);\n'
                                   '')
        self.ordinal.setChecked(True)
        self.ordinal.setObjectName('ordinal')
        self.horizontalLayout_5.addWidget(self.ordinal)
        self.random = QtWidgets.QRadioButton(self.types)
        self.random.setStyleSheet('    border-style: solid;\n'
                                  '    border-color: rgb(0, 0, 0);\n'
                                  '    border-width: 1px;\n'
                                  '    border-radius: 8px;\n'
                                  'background-color: rgb(85, 87, 83);\n'
                                  '')
        self.random.setObjectName('random')
        self.horizontalLayout_5.addWidget(self.random)
        self.verticalLayout_5.addWidget(self.types)
        self.verticalLayout_3.addWidget(self.type_changing)
        self.nicknames_set = QtWidgets.QFrame(self.body)
        self.nicknames_set.setStyleSheet('QFrame {\n'
                                         '    border-style: solid;\n'
                                         '    border-color: rgb(0, 0, 0);\n'
                                         '    border-width: 1px;\n'
                                         '    border-radius: 8px;\n'
                                         '    background-color: rgb(40, 38, 38);\n'
                                         '}\n'
                                         '')
        self.nicknames_set.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nicknames_set.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nicknames_set.setObjectName('nicknames_set')
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.nicknames_set)
        self.verticalLayout_4.setObjectName('verticalLayout_4')
        self.nickname_set = QtWidgets.QLabel(self.nicknames_set)
        self.nickname_set.setStyleSheet('border:none;\n'
                                        'color:white')
        self.nickname_set.setObjectName('nickname_set')
        self.verticalLayout_4.addWidget(self.nickname_set)
        self.nicknames_list = QtWidgets.QPlainTextEdit(self.nicknames_set)
        self.nicknames_list.setStyleSheet('border:none;\n'
                                          'background-color: rgb(243, 243, 243);')
        self.nicknames_list.setObjectName('nicknames_list')
        self.verticalLayout_4.addWidget(self.nicknames_list)
        self.verticalLayout_3.addWidget(self.nicknames_set)
        self.btn_start = QtWidgets.QPushButton(self.body)
        self.btn_start.setStyleSheet('.QPushButton {\n'
                                     '    border: none;\n'
                                     '    border-radius: 13px;\n'
                                     '    border-style: solid;\n'
                                     '    color: rgb(255, 255, 255);\n'
                                     '    border-color: rgb(0, 0, 0);\n'
                                     '    border-width: 1px;\n'
                                     '    background-color: rgb(18, 150, 38);\n'
                                     '    padding: 7px;\n'
                                     '    width: 55px;\n'
                                     '}\n'
                                     '.QPushButton:hover {\n'
                                     '    background-color: rgb(13, 118, 29);\n'
                                     '}\n'
                                     '')
        self.btn_start.setObjectName('btn_start')
        self.verticalLayout_3.addWidget(
            self.btn_start, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.body)
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName('footer')
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.version = QtWidgets.QFrame(self.footer)
        self.version.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.version.setFrameShadow(QtWidgets.QFrame.Raised)
        self.version.setObjectName('version')
        self.gridLayout = QtWidgets.QGridLayout(self.version)
        self.gridLayout.setObjectName('gridLayout')
        self.labelversion = QtWidgets.QLabel(self.version)
        self.labelversion.setObjectName('labelversion')
        self.gridLayout.addWidget(
            self.labelversion, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.version)
        self.author = QtWidgets.QFrame(self.footer)
        self.author.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.author.setFrameShadow(QtWidgets.QFrame.Raised)
        self.author.setObjectName('author')
        self.gridLayout_4 = QtWidgets.QGridLayout(self.author)
        self.gridLayout_4.setObjectName('gridLayout_4')
        self.labelauthor = QtWidgets.QLabel(self.author)
        self.labelauthor.setObjectName('labelauthor')
        self.gridLayout_4.addWidget(
            self.labelauthor, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.author)
        self.verticalLayout.addWidget(self.footer)
        StartWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartWin)
        QtCore.QMetaObject.connectSlotsByName(StartWin)

    def retranslateUi(self, StartWin):
        _translate = QtCore.QCoreApplication.translate
        StartWin.setWindowTitle(_translate('StartWin', 'MainWindow'))
        self.label.setText(_translate('StartWin', 'SteamNameChanger'))
        self.label_username.setText(_translate('StartWin', 'Username'))
        self.label_3.setText(_translate('StartWin', 'Interval (seconds):'))
        self.comboBox.setItemText(0, _translate('StartWin', '60'))
        self.comboBox.setItemText(1, _translate('StartWin', '120'))
        self.comboBox.setItemText(2, _translate('StartWin', '125'))
        self.comboBox.setItemText(3, _translate('StartWin', '130'))
        self.comboBox.setItemText(4, _translate('StartWin', '150'))
        self.label_types.setText(_translate('StartWin', 'Type of changing: '))
        self.ordinal.setText(_translate('StartWin', 'Ordinal'))
        self.random.setText(_translate('StartWin', 'Random'))
        self.nickname_set.setText(_translate(
            'StartWin', 'Nicknames set (through a comma):'))
        self.nicknames_list.setPlainText(_translate('StartWin', 'Example 1,\n'
                                                                'Example 2,\n'
                                                                'Example 3\n'
                                                                ''))
        self.btn_start.setText(_translate('StartWin', 'Start'))
        self.labelversion.setText(_translate('StartWin', 'v 1.0'))
        self.labelauthor.setText(_translate('StartWin', 'by NightExpress'))
