# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/skeletons/ui_forms/statistic.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatisticWindow(object):
    def setupUi(self, StatisticWindow):
        StatisticWindow.setObjectName('StatisticWindow')
        StatisticWindow.resize(327, 458)
        self.centralwidget = QtWidgets.QWidget(StatisticWindow)
        self.centralwidget.setStyleSheet('border: none;\n'
                                         'background-color: rgb(56, 55, 52);')
        self.centralwidget.setObjectName('centralwidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.title_bar = QtWidgets.QFrame(self.centralwidget)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 40))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_bar.setStyleSheet('QFrame {\n'
                                     '    border:none;\n'
                                     '    \n'
                                     '    background-color: rgb(85, 87, 83);\n'
                                     '}\n'
                                     '')
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName('title_bar')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName('frame_title')
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_3.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.label = QtWidgets.QLabel(self.frame_title)
        self.label.setStyleSheet("font: 75 11pt \"Ubuntu Mono\";\n"
                                 'font: bold;\n'
                                 '')
        self.label.setObjectName('label')
        self.verticalLayout_3.addWidget(
            self.label, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName('frame_btns')
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.btn_hide = QtWidgets.QPushButton(self.frame_btns)
        self.btn_hide.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_hide.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_hide.setStyleSheet('QPushButton {\n'
                                    '    background-color: rgb(237, 212, 0);\n'
                                    '    border: none;\n'
                                    '    border-radius: 10px;\n'
                                    '    border-style: solid;\n'
                                    '    border-color: rgb(0, 0, 0);\n'
                                    '    border-width: 1px;\n'
                                    '    \n'
                                    '}\n'
                                    'QPushButton:hover {\n'
                                    '    background-color: rgb(196, 160, 0);\n'
                                    '}\n'
                                    '\n'
                                    '\n'
                                    '')
        self.btn_hide.setText('')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ':/custom/custom/icons8-horizontal-line-24.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hide.setIcon(icon)
        self.btn_hide.setIconSize(QtCore.QSize(16, 16))
        self.btn_hide.setObjectName('btn_hide')
        self.horizontalLayout_2.addWidget(self.btn_hide)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_close.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_close.setStyleSheet('QPushButton {\n'
                                     '    border: none;\n'
                                     '    border-radius: 10px;\n'
                                     '    background-color: rgb(204, 0, 0);\n'
                                     '    border-style: solid;\n'
                                     '    border-color: rgb(0, 0, 0);\n'
                                     '    border-width: 1px;\n'
                                     '}\n'
                                     'QPushButton:hover {\n'
                                     '    background-color: rgb(164, 0, 0);\n'
                                     '}')
        self.btn_close.setText('')
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            ':/custom/custom/icons8-close.svg'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setObjectName('btn_close')
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName('body')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.username = QtWidgets.QFrame(self.body)
        self.username.setMaximumSize(QtCore.QSize(16777215, 50))
        self.username.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username.setObjectName('username')
        self.gridLayout_2 = QtWidgets.QGridLayout(self.username)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.label_username = QtWidgets.QLabel(self.username)
        self.label_username.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_username.setStyleSheet('font: bold;\n'
                                          'font-size: 30px;\n'
                                          'height: 48px;\n'
                                          'width: 120px;')
        self.label_username.setObjectName('label_username')
        self.gridLayout_2.addWidget(
            self.label_username, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.username)
        self.statuses = QtWidgets.QFrame(self.body)
        self.statuses.setStyleSheet('QFrame {\n'
                                    '    border-style: solid;\n'
                                    '    border-color: rgb(0, 0, 0);\n'
                                    '    border-width: 1px;\n'
                                    '    border-radius: 8px;\n'
                                    '    background-color: rgb(40, 38, 38);\n'
                                    '    color: rgb(238, 238, 236);\n'
                                    '}\n'
                                    '')
        self.statuses.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statuses.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statuses.setObjectName('statuses')
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.statuses)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.keys = QtWidgets.QFrame(self.statuses)
        self.keys.setStyleSheet('border: none;\n'
                                '')
        self.keys.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keys.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keys.setObjectName('keys')
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.keys)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName('verticalLayout_5')
        self.label_current_nick = QtWidgets.QLabel(self.keys)
        self.label_current_nick.setObjectName('label_current_nick')
        self.verticalLayout_5.addWidget(
            self.label_current_nick, 0, QtCore.Qt.AlignRight)
        self.label_counter = QtWidgets.QLabel(self.keys)
        self.label_counter.setObjectName('label_counter')
        self.verticalLayout_5.addWidget(
            self.label_counter, 0, QtCore.Qt.AlignRight)
        self.label_last = QtWidgets.QLabel(self.keys)
        self.label_last.setObjectName('label_last')
        self.verticalLayout_5.addWidget(
            self.label_last, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_4.addWidget(self.keys)
        self.values = QtWidgets.QFrame(self.statuses)
        self.values.setStyleSheet('border: none;\n'
                                  'font-weight: bold;')
        self.values.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.values.setFrameShadow(QtWidgets.QFrame.Raised)
        self.values.setObjectName('values')
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.values)
        self.verticalLayout_4.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName('verticalLayout_4')
        self.value_current_nick = QtWidgets.QLabel(self.values)
        self.value_current_nick.setObjectName('value_current_nick')
        self.verticalLayout_4.addWidget(self.value_current_nick)
        self.value_counter = QtWidgets.QLabel(self.values)
        self.value_counter.setObjectName('value_counter')
        self.verticalLayout_4.addWidget(self.value_counter)
        self.value_last = QtWidgets.QLabel(self.values)
        self.value_last.setObjectName('value_last')
        self.verticalLayout_4.addWidget(self.value_last)
        self.horizontalLayout_4.addWidget(self.values)
        self.verticalLayout_2.addWidget(self.statuses)
        self.logs = QtWidgets.QFrame(self.body)
        self.logs.setStyleSheet('QFrame {\n'
                                '    border-style: solid;\n'
                                '    border-color: rgb(0, 0, 0);\n'
                                '    border-width: 1px;\n'
                                '    border-radius: 8px;\n'
                                '    background-color: rgb(40, 38, 38);\n'
                                '    color: rgb(238, 238, 236);\n'
                                '}\n'
                                '')
        self.logs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logs.setObjectName('logs')
        self.gridLayout_5 = QtWidgets.QGridLayout(self.logs)
        self.gridLayout_5.setContentsMargins(-1, 3, -1, -1)
        self.gridLayout_5.setObjectName('gridLayout_5')
        self.text_logs = QtWidgets.QTextBrowser(self.logs)
        self.text_logs.setStyleSheet('border: none;\n'
                                     'background-color: rgb(211, 215, 207);\n'
                                     'color: rgb(0, 0, 0);')
        self.text_logs.setObjectName('text_logs')
        self.gridLayout_5.addWidget(self.text_logs, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.logs)
        self.label_2.setStyleSheet('border: none')
        self.label_2.setObjectName('label_2')
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.logs)
        self.stop = QtWidgets.QFrame(self.body)
        self.stop.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stop.setObjectName('stop')
        self.gridLayout_3 = QtWidgets.QGridLayout(self.stop)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName('gridLayout_3')
        self.btn_stop = QtWidgets.QPushButton(self.stop)
        self.btn_stop.setStyleSheet('.QPushButton {\n'
                                    '    border: none;\n'
                                    '    border-radius: 13px;\n'
                                    '    border-style: solid;\n'
                                    '    color: rgb(0, 0, 0);\n'
                                    '    border-color: rgb(0, 0, 0);\n'
                                    '    border-width: 1px;\n'
                                    '    background-color: rgb(204, 0, 0);\n'
                                    '    padding: 7px;\n'
                                    '    width: 55px;\n'
                                    '}\n'
                                    '.QPushButton:hover {\n'
                                    '    background-color: rgb(164, 0, 0);\n'
                                    '}\n'
                                    '')
        self.btn_stop.setObjectName('btn_stop')
        self.gridLayout_3.addWidget(self.btn_stop, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.stop, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.body)
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName('footer')
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.version = QtWidgets.QFrame(self.footer)
        self.version.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.version.setFrameShadow(QtWidgets.QFrame.Raised)
        self.version.setObjectName('version')
        self.gridLayout = QtWidgets.QGridLayout(self.version)
        self.gridLayout.setObjectName('gridLayout')
        self.labelversion = QtWidgets.QLabel(self.version)
        self.labelversion.setObjectName('labelversion')
        self.gridLayout.addWidget(
            self.labelversion, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.version)
        self.author = QtWidgets.QFrame(self.footer)
        self.author.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.author.setFrameShadow(QtWidgets.QFrame.Raised)
        self.author.setObjectName('author')
        self.gridLayout_4 = QtWidgets.QGridLayout(self.author)
        self.gridLayout_4.setObjectName('gridLayout_4')
        self.labelauthor = QtWidgets.QLabel(self.author)
        self.labelauthor.setObjectName('labelauthor')
        self.gridLayout_4.addWidget(
            self.labelauthor, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.author)
        self.verticalLayout.addWidget(self.footer)
        StatisticWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StatisticWindow)
        QtCore.QMetaObject.connectSlotsByName(StatisticWindow)

    def retranslateUi(self, StatisticWindow):
        _translate = QtCore.QCoreApplication.translate
        StatisticWindow.setWindowTitle(
            _translate('StatisticWindow', 'MainWindow'))
        self.label.setText(_translate('StatisticWindow', 'SteamNameChanger'))
        self.label_username.setText(_translate('StatisticWindow', 'Username'))
        self.label_current_nick.setText(_translate(
            'StatisticWindow', 'Current nickname:'))
        self.label_counter.setText(_translate(
            'StatisticWindow', 'Counter of changes:'))
        self.label_last.setText(_translate('StatisticWindow', 'Last update:'))
        self.value_current_nick.setText(_translate('StatisticWindow', 'N/A'))
        self.value_counter.setText(_translate('StatisticWindow', 'N/A'))
        self.value_last.setText(_translate('StatisticWindow', 'N/A'))
        self.text_logs.setHtml(_translate(
            'StatisticWindow',
            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
            'p, li { white-space: pre-wrap; }\n'
            "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; "
            "-qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate('StatisticWindow', 'Logs:'))
        self.btn_stop.setText(_translate('StatisticWindow', 'STOP'))
        self.labelversion.setText(_translate('StatisticWindow', 'v 1.0'))
        self.labelauthor.setText(_translate(
            'StatisticWindow', 'by NightExpress'))
